include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: false

    #! OTHER CUSTOM LINT RULES
    avoid_init_to_null: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_typing_uninitialized_variables: true
    avoid_redundant_argument_values: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    sort_child_properties_last: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    avoid_renaming_method_parameters: true
    avoid_positional_boolean_parameters: true
    prefer_const_declarations: true
    avoid_dynamic_calls: true
    avoid_function_literals_in_foreach_calls: true
    #public_member_api_docs: true
    always_put_required_named_parameters_first: true
    camel_case_types: true
    constant_identifier_names: true
    library_prefixes: true

analyzer:
  plugins:
    - custom_lint
