name: serti0x_blog_editor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #!STATE MANAGEMENT AND SUPPORTING UTILS
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3

  #! AUTH AND OTHER INTERNET UTILS
  google_sign_in: ^6.2.1
  http: ^1.2.1
  socket_io_client: ^2.0.3+1

  #! NAVIGATION
  routemaster: ^1.0.1

  #! OTHER UTILS
  flutter_quill: ^9.3.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  #! LINTERS
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.6
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
