name: serti0x_blog_editor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  avatar_glow: ^3.0.1
  flutter:
    sdk: flutter

  #! ANIMATIONS
  flutter_animate: ^4.5.0
  flutter_dotenv: ^5.1.0

  #! OTHER UTILS
  flutter_quill: ^9.3.21
  cool_dropdown: ^2.1.0

  #!STATE MANAGEMENT AND SUPPORTING UTILS
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.8.3
  flutter_svg: ^2.0.10+1

  #! AUTH AND OTHER INTERNET UTILS
  google_sign_in: ^6.2.1
  #google_sign_in: ^5.4.1
  http: ^1.2.1
  intl: ^0.19.0

  #! NAVIGATION
  routemaster: ^1.0.1
  shared_preferences: ^2.2.3
  socket_io_client: ^2.0.3+1

dev_dependencies:
  custom_lint: ^0.6.4

  #! LINTERS
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/gif/
    - .env

  fonts:
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Italic.ttf
    - family: Eudoxus Sans
      fonts:
        - asset: assets/fonts/EudoxusSans-Regular.ttf
        - asset: assets/fonts/EudoxusSans-Medium.ttf
        - asset: assets/fonts/EudoxusSans-Bold.ttf
        - asset: assets/fonts/EudoxusSans-ExtraBold.ttf
